### ISSUE TITLE
代码没问题但是报错 NoSuchMethodError

### ISSUE THREAD

**Issue by hyoban** [hyoban/hyoban.github.io#11]
如果你的代码没有错误，但是运行闪退，可能的原因是使用了版本不兼容的 compose 依赖库

`java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes`

## 参考

[java.lang.NoSuchMethodError after upgrading Jetpack Compose to 1.0.0‑beta07](https://stackoverflow.com/questions/67611497)
